# Generated by Django 3.0.3 on 2020-03-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('prepareTime', models.PositiveSmallIntegerField()),
                ('difficultyLevel', models.CharField(max_length=20, verbose_name='Level of difficulty')),
                ('numberOfPortions', models.PositiveSmallIntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StepInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('instruction', models.CharField(max_length=1000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='StepIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unit', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('pc.', 'piece'), ('pinch', 'pinch'), ('tbsp', 'tablespoon'), ('ml', 'milliliters'), ('tsp.', 'teaspoon'), ('cloves', 'cloves')], max_length=20, verbose_name='Units')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('kcalPerUnit', models.SmallIntegerField(verbose_name='KCAL per unit')),
                ('carboPerUnit', models.SmallIntegerField(verbose_name='Carbohydrates grams per unit')),
                ('proteinPerUnit', models.SmallIntegerField(verbose_name='Proteins grams per unit')),
                ('fatPerUnit', models.SmallIntegerField(verbose_name='Fats grams per unit')),
                ('steps', models.ManyToManyField(to='recipes.StepIngredients')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
