# Generated by Django 3.0.3 on 2020-03-04 09:30

from django.db import migrations
from ..models import Recipe


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial')
    ]

    operations = [
    ]
