# Generated by Django 3.0.3 on 2020-03-04 09:30

from django.db import migrations
from ..models import Recipe


def create_data(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    crispyChicken = Recipe(name="Crispy chicken", description="Very crispy chicken", prepareTime=100,
                           difficultyLevel="low", numberOfPortions=2, likes=2)
    crispyChicken.save()
    Ingredient = apps.get_model('recipes', 'Ingredient')
    StepIngredients = apps.get_model('recipes', 'StepIngredients')
    StepInstructions = apps.get_model('recipes', 'StepInstructions')
    chicken = Ingredient(name="chicken", unit="kg", quantity=0.7, kcalPerUnit=164, carboPerUnit=0.1, proteinPerUnit=124,
                         fatPerUnit=29.8,
                         )
    chicken.save()
    coating = Ingredient(name="coating", unit="g", quantity=100, kcalPerUnit=4, carboPerUnit=4, proteinPerUnit=0,
                         fatPerUnit=0)
    coating.save()
    oil = Ingredient(name="oil", unit="ml", quantity=9, kcalPerUnit=9, carboPerUnit=0, proteinPerUnit=0,
                     fatPerUnit=9)
    oil.save()
    breading = StepIngredients(recipe=crispyChicken, name="Breading chicken")
    breading.save()
    frying = StepIngredients(recipe=crispyChicken, name="Frying chicken")
    frying.save()
    breadingInstructions = StepInstructions(recipe=crispyChicken, name="Breading chicken",
                                            instruction="Slice chicken and bread it in coating put on a plate. You may use your favourite seasoning").save()
    fryingInstructions = StepInstructions(recipe=crispyChicken, name="Frying chicken",
                                          instruction="Fry chicken in hot oil for about 10 minutes").save()
    chicken.steps.add(breading)
    coating.steps.add(breading)
    oil.steps.add(frying)


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
