# Generated by Django 3.0.3 on 2020-03-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='steps',
            field=models.ManyToManyField(related_name='ingredient', to='recipes.StepIngredients'),
        ),
        migrations.AlterField(
            model_name='stepingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepIngredients', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='stepinstructions',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.Recipe'),
        ),
    ]
