# Generated by Django 3.0.3 on 2020-04-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200402_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='steps',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.StepIngredients'),
        ),
    ]
